[phases.setup]
nixPkgs = ["nodejs_18"]

[phases.install]
cmds = [
  "cd backend && npm ci"
]

[phases.build]
cmds = [
  "cd backend && npx prisma generate",
  "cd backend && npx prisma db push --force-reset"
]

[start]
cmd = "cd backend && npm start"
